# Generated by Django 6.0.1 on 2026-02-02 17:15

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_job_description_alter_job_raw_html_jobevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], default='submitted', max_length=12)),
                ('date_status_changed', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('old_status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('text', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
