# Generated by Django 6.0.1 on 2026-02-03

import sisyphus.core.fields
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(editable=False)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(editable=False)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('match_mode', models.CharField(choices=[('all', 'All conditions must match'), ('any', 'Any condition matches')], default='all', max_length=3)),
                ('target_status', models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(editable=False)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(editable=False)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('company', 'Company'), ('location', 'Location'), ('url', 'URL')], max_length=11)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('exact', 'Exact match'), ('regex', 'Regular expression'), ('not_contains', 'Does not contain')], default='contains', max_length=12)),
                ('value', models.CharField(max_length=500)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(editable=False)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(editable=False)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('old_status', models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='jobs.job')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rules.rule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
