# Generated by Django 5.2.4 on 2025-07-20 21:43

import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('contains', 'Contains')], default='contains', max_length=8)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
