# Generated by Django 5.2.4 on 2025-07-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='field_type',
        ),
    ]
