# Generated by Django 6.0.1 on 2026-02-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='target_status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], default='filtered', max_length=12),
        ),
    ]
