# Generated by Django 5.2.4 on 2025-07-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_remove_rule_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
