# Generated by Django 6.0.1 on 2026-02-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rule_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulematch',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='rules.rule'),
        ),
    ]
