# Generated by Django 6.0.1 on 2026-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_rulematch_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulematch',
            options={},
        ),
    ]
