# Generated by Django 5.2.4 on 2025-07-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='populated',
            field=models.BooleanField(default=True),
        ),
    ]
