# Generated by Django 5.2.4 on 2025-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rule_populated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='populated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
