# Generated by Django 6.0.1 on 2026-02-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_rulematch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('-priority', 'name')},
        ),
    ]
