# Generated by Django 6.0.1 on 2026-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_rule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority rules are evaluated first'),
        ),
    ]
