# Generated by Django 5.2.4 on 2025-07-19 00:04

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('keywords', models.CharField(max_length=255)),
                ('easy_apply', models.BooleanField(default=False)),
                ('flexibility', models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=6)),
                ('period', models.IntegerField(choices=[(2592000, 'Monthly'), (604800, 'Weekly'), (86400, 'Daily'), (3600, 'Hourly'), (900, 'Quarter Hourly')], default=604800)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to='jobs.location')),
            ],
            options={
                'verbose_name': 'search',
                'verbose_name_plural': 'searches',
            },
        ),
    ]
