# Generated by Django 6.0.1 on 2026-02-08 22:07

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0008_alter_job_flexibility_alter_job_pre_ban_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('parser', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('keywords', models.CharField(max_length=255)),
                ('easy_apply', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('is_onsite', models.BooleanField(default=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=9)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to='jobs.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='searches.source')),
            ],
            options={
                'verbose_name': 'search',
                'verbose_name_plural': 'searches',
            },
        ),
    ]
