# Generated by Django 6.0.1 on 2026-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=7),
        ),
    ]
