# Generated by Django 6.0.1 on 2026-02-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0004_alter_search_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
