# Generated by Django 6.0.1 on 2026-02-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0008_alter_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='schedule',
            field=models.CharField(blank=True, default='', help_text='Cron expression (e.g. "0 */6 * * *" for every 6 hours). Leave blank to disable.', max_length=100),
        ),
    ]
