# Generated by Django 6.0.1 on 2026-02-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_default_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_resume',
        ),
    ]
