# Generated by Django 6.0.1 on 2026-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_default_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_application_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
