# Generated by Django 6.0.1 on 2026-02-03 00:08

import django.db.models.deletion
import sisyphus.core.fields
import sisyphus.resumes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='A label for this resume (e.g., "Software Engineer Resume")', max_length=255)),
                ('file', models.FileField(upload_to=sisyphus.resumes.models.resume_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
