# Generated by Django 6.0.1 on 2026-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, help_text='Extracted text content from the resume'),
        ),
    ]
