# Generated by Django 6.0.1 on 2026-02-03 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_default_resume'),
        ('resumes', '0002_resume_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='accounts.userprofile'),
        ),
    ]
