# Generated by Django 5.2.4 on 2025-07-18 23:47

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('banned', models.BooleanField(default=False)),
                ('banned_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('geo_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateField()),
                ('date_found', models.DateField()),
                ('populated', models.BooleanField(default=False)),
                ('easy_apply', models.BooleanField(default=False)),
                ('flexibility', models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
