# Generated by Django 6.0.1 on 2026-02-02 16:37

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('geo_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('date_found', models.DateTimeField(blank=True, null=True)),
                ('populated', models.BooleanField(default=False)),
                ('flexibility', models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default=None, max_length=6, null=True)),
                ('raw_html', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('easy_apply', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=9)),
                ('date_status_changed', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
