# Generated by Django 5.2.4 on 2025-07-19 01:58

import django.db.models.deletion
import sisyphus.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_date_applied_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', sisyphus.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', sisyphus.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', sisyphus.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('event_type', models.CharField(choices=[('note', 'Note'), ('status', 'Status')], max_length=6)),
                ('old_status', models.CharField(blank=True, max_length=10, null=True)),
                ('new_status', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_events', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
