# Generated by Django 6.0.1 on 2026-02-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_description_alter_job_raw_html_jobevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=9),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='new_status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], max_length=9),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='old_status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], max_length=9),
        ),
    ]
