# Generated by Django 5.2.4 on 2025-07-19 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_event'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='search.search'),
        ),
    ]
