# Generated by Django 6.0.1 on 2026-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_status_alter_jobevent_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pre_ban_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], max_length=9, null=True),
        ),
    ]
