# Generated by Django 5.2.4 on 2025-07-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=10),
        ),
    ]
