# Generated by Django 6.0.1 on 2026-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_pre_ban_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pre_ban_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='new_status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='old_status',
            field=models.CharField(choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], max_length=12),
        ),
    ]
