# Generated by Django 6.0.1 on 2026-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_pre_ban_status_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='score_explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
