# Generated by Django 6.0.1 on 2026-02-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_score_job_score_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
