# Generated by Django 6.0.1 on 2026-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_score_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='flexibility',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='job',
            name='pre_ban_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('filtered', 'Filtered'), ('banned', 'Banned'), ('saved', 'Saved'), ('expired', 'Expired'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('accepted', 'Accepted')], default='', max_length=12),
        ),
    ]
