# Generated by Django 6.0.1 on 2026-02-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_flexibility_alter_job_pre_ban_status'),
        ('searches', '0005_searchrun_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='searches.searchrun'),
        ),
    ]
