# Generated by Django 6.0.1 on 2026-02-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_default_resume'),
        ('companies', '0003_company_user_alter_company_linkedin_url_and_more'),
        ('jobs', '0009_job_search_run'),
        ('searches', '0005_searchrun_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('url', 'user'), name='unique_job_url_per_user'),
        ),
    ]
