# Generated by Django 6.0.1 on 2026-02-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_create_locations'),
        ('searches', '0009_search_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='searches.source'),
        ),
    ]
