# Generated by Django 6.0.1 on 2026-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='similar_jobs_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
